<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

/**
* Grouped product data template
*
* @var $block \Magento\Catalog\Block\Product\View\BaseImage
* @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
*/
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />

<style>
@media only screen and (max-width: 768px) {
  .colhider {
	display: none;
	}
	.addbutt {
	margin-top: 2px;
	}
}
@media only screen and (min-width: 768px) {
  .colshower {
	display: none;
	}
}
.colhider td, .colshower td {
	vertical-align: middle !important;
}
.addbutt {
	padding: 0px 5px;
	height: 37px;
	line-height: 0;
}
input[type="number"] {
	-webkit-appearance: textfield;
	-moz-appearance: textfield;
	appearance: textfield;
}
input[type=number]::-webkit-inner-spin-button, input[type=number]::-webkit-outer-spin-button {
	-webkit-appearance: none;
}
.number-input {
	border: 1px solid #d1d1d1;
	display: inline-flex;
	border-radius: 3px;
}
.number-input a {
	font: 17px/2.0 Arial,Helvetica,sans-serif;
	font-weight: 600;
	cursor: pointer;
	display: block;
	padding: 0px 8px;
	background-color: #f6f6f6;
	border-color: #e2e2e2;
	border-radius: 3px;
	user-select: none; /* supported by Chrome and Opera */
	-webkit-user-select: none; /* Safari */
	-khtml-user-select: none; /* Konqueror HTML */
	-moz-user-select: none; /* Firefox */
	-ms-user-select: none; /* Internet Explorer/Edge */
}

/* Hides large Add to Cart button below grouped product table*/
#product-addtocart-button {
	display: none;
}
.hovimg img {
	z-index:100;
	border:1px solid #d1d1d1;
	opacity: 1;
}
.hovimg img:hover {
  opacity: 0.6;
}
</style>

<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $grouped = $_product->load($_product->getId()); ?>
<?php $associatedProducts = $grouped->getTypeInstance()->getAssociatedProducts($grouped); ?>

<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$categories = $product->getCategoryIds(); /*will return category ids array*/
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    #echo $cat->getId();
	
	if ($cat->getId() == '27') { # DONE  ----------  CHANGE THIS WHEN I KNOW WHAT THE SHEET PRODUCT CATEGORY IS
	$tableNum = '1';
	} else {
	$tableNum = '0';
    };
};
?>
</form>

<div class="table-wrapper grouped">

<div class="colshower" style="font-size:12px;">
<p><i>You may need to Scroll Left and Right for more product details</i></p>
</div>

<table class="table data grouped hovimg" id="super-product-table">
<caption class="table-caption"><?= /* @escapeNotVerified */ __('Grouped product items') ?></caption>
	<thead>
		<?php if ($tableNum == '0'){ ?>
			<tr class="colhider"> <!-- Hidden on mobile -->
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Image') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('CAD Image') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('SKU') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Finish') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Grade') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Size') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
				<?php if ($_product->isSaleable()): ?>
					<th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
				<?php endif; ?>
				<th></th>
			</tr>
			
			<tr class="colshower"> <!-- Shown on mobile -->
				<?php if ($_product->isSaleable()): ?>
					<th class="col qty" scope="col" colspan="2"><?= /* @escapeNotVerified */ __('Qty') ?></th>
				<?php endif; ?>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Finish') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Grade') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Size') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('SKU') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Image') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('CAD Image') ?></th>
				<th></th>
			</tr>

		<?php } else { ?>
			<tr>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Image') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('CAD Image') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('SKU') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Finish') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Grade') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Thickness') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Pitch') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Open Area') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('AWG') ?></th>
				<th class="col item colhider" scope="col"><?= /* @escapeNotVerified */ __('') ?></th>
				<th class="col item" scope="col"><?= /* @escapeNotVerified */ __('Price') ?></th>
				<?php if ($_product->isSaleable()): ?>
					<th class="col qty" scope="col"><?= /* @escapeNotVerified */ __('Qty') ?></th>
				<?php endif; ?>
				<th></th>
			</tr>
		<?php }; ?>
	</thead>

<?php if ($_hasAssociatedProducts){ ?>
	<?php foreach ($associatedProducts as $_item): ?>
		<tbody>
			
			<?php if ($tableNum == '0'): ?> 
				
				<!-- Hidden on mobile ---------------------------------------------------------------------------------------->
				<tr class="colhider"> 
				
					<td>
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsDesktop" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $image_url; ?>" />
						</a>
					</td>
				
					
					<td  class="colhider">
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsDesktop" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $lrg_image_url; ?>" />
						</a>
					</td>


					<td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col item">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getSku()) ?></strong>
					</td>
					

					<td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item colhider" >
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
					</td>
					
					
					<td data-th="<?php echo $block->escapeHtml(__('Finish')) ?>" class="col item">
						<?php					
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'finish',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('finish');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = 'N/A';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?> </span>
					</td>

					
					<td data-th="<?php echo $block->escapeHtml(__('Grade')) ?>" class="col item">
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'grade',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('grade');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = 'N/A';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</td>
					
					
					<td data-th="<?php echo $block->escapeHtml(__('Size')) ?>" class="col item" >
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'size',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('size');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = 'N/A';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</td>

					
					<td data-th="<?php echo $block->escapeHtml(__('')) ?>" class="col item colhider">
						<?php $addit = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'additinfo',$_item->getId()); ?>
						<span class="product-item-name"><?php try { echo $addit; } catch (Exception $e) { unset($e); } ?></span>
						<?php $addit = ''; ?>
					</td>
					
					
					<td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col item">
						<?php if ($block->getCanShowProductPrice($_product)): ?>
							<?php if ($block->getCanShowProductPrice($_item)): ?>
								<?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
							<?php endif; ?>
						<?php endif; ?>
					</td>
					

					<?php if ($_product->isSaleable()): ?>
						<td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
							<?php if ($_item->isSaleable()) : ?>
								<div class="control qty">
									<form data-role="tocart-form" action="<?php echo $this->getAddToCartUrl($_item); ?>" method="post">
										<input type="hidden" name="product" value="<?php echo $_item->getId(); ?>">
										<input type="hidden" name="related_product" id="related-products-field" value="">
										<div class="number-input">
											<a onclick="this.nextElementSibling.stepDown()" >&minus;</a>
												<input type="number" name="qty" min="1" value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>" title="<?= /* @escapeNotVerified */ __('Qty') ?>" class="input-text qty required" />
											<a onclick="this.previousElementSibling.stepUp()">+</a>
										</div>
										<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit" title="Add to Cart" class="addtocart addbutt">Add <span class="fa fa-shopping-basket crat-icon"></span></button>

										
									</form>
								</div>

								<?php else: ?>
								<div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
								<span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
								</div>
							<?php endif; ?>
						</td>
						<td class="addtocart">
						</td>
					<?php endif; ?>
				</tr>
				<!-- END Hidden on mobile ------------------------------------------------------------------------------------>
				
				
				<!-- Shown on mobile ------------------------------------------------------------------------------------------>
				<tr class="colshower">
					
					<?php if ($_product->isSaleable()): ?>
						<td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty" style="align-content: center;">
							<?php if ($_item->isSaleable()) : ?>
								<div class="control qty">
									<form data-role="tocart-form" action="<?php echo $this->getAddToCartUrl($_item); ?>" method="post">
										<input type="hidden" name="product" value="<?php echo $_item->getId(); ?>">
										<input type="hidden" name="related_product" id="related-products-field" value="">
										<div class="number-input">
											<a onclick="this.nextElementSibling.stepDown()" >&minus;</a>
												<input type="number" name="qty" min="1" value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>" title="<?= /* @escapeNotVerified */ __('Qty') ?>" class="input-text qty required" />
											<a onclick="this.previousElementSibling.stepUp()">+</a>
										</div>									<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit" title="Add to Cart" class="addtocart addbutt">Add <span class="fa fa-shopping-basket crat-icon"></span></button>
									</form>
								</div>

								<?php else: ?>
								<div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
								<span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
								</div>
							<?php endif; ?>
						</td>
						<td class="addtocart">
						</td>
					<?php endif; ?>
					
					
					<td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col item">
						<?php if ($block->getCanShowProductPrice($_product)): ?>
							<?php if ($block->getCanShowProductPrice($_item)): ?>
								<?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
							<?php endif; ?>
						<?php endif; ?>
					</td>
					

					<td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item colhider">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
					</td>
					
					
					<td data-th="<?php echo $block->escapeHtml(__('Finish')) ?>" class="col item">
						<?php					
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'finish',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('finish');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = 'N/A';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?> </span>
					</td>

					
					<td data-th="<?php echo $block->escapeHtml(__('Grade')) ?>" class="col item" >
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'grade',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('grade');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = 'N/A';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</td>
					
					
					<td data-th="<?php echo $block->escapeHtml(__('Size')) ?>" class="col item">
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'size',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('size');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = 'N/A';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</td>

					
					<td data-th="<?php echo $block->escapeHtml(__('')) ?>" class="col item colhider" >
						<?php $addit = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'additinfo',$_item->getId());	?>
						<span class="product-item-name"><?php try { echo $addit; } catch (Exception $e) { unset($e); } ?></span>
						<?php $addit = ''; ?>
					</td>
					
					
					<td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col item">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getSku()) ?></strong>
					</td>
					
					<td class="colhider">
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsMobile" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $image_url; ?>" />
						</a>
					</td>
				
					
					<td>
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsMobile" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $lrg_image_url; ?>" />
						</a>
					</td>
					
					
					
				</tr>
				<!-- END Shown on mobile -------------------------------------------------------------------------------------->
				
<!-- SHEET PRODUCT TABLE BELOW HERE ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
			<?php else: # --------------------------------------------------------------------------------------------------------------------------- ?>
			
				<tr>
				
					<td>
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsSheet" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $image_url; ?>" />
						</a>
					</td>
				
				
					<td class="colhider">
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsSheet" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $lrg_image_url; ?>" />
						</a>
					</td>
					

					<td data-th="<?= $block->escapeHtml(__('SKU')) ?>" class="col item" >
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getSku()) ?></strong>
					</td>
					
					
					<td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col item colhider" >
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
					</td>
					
					
					<?php if ($_product->isSaleable()): ?>
					
						<td data-th="<?php echo $block->escapeHtml(__('Finish')) ?>" class="col item" >
							<?php
								$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'finish',$_item->getId());
								$optionId = $my_attr;
								$attribute = $_product->getResource()->getAttribute('finish');
								if (is_string($optionId)) {
									//pass
								} elseif (is_array($optionId)) {
									$optionId = '';
								} else {
									$optionId = '';
								};
								if ($attribute->usesSource()) {
									$optionText = $attribute->getSource()->getOptionText($optionId);
								};
								if (strlen($optionText) > 1 ){
								} else {
									$optionText = 'N/A';
								};
							?>
							<span class="product-item-name"><?php echo $optionText; ?></span>
						</td>

						
						<td data-th="<?php echo $block->escapeHtml(__('Grade')) ?>" class="col item" >
							<?php
								$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'grade',$_item->getId());
								$optionId = $my_attr;
								$attribute = $_product->getResource()->getAttribute('grade');
								if (is_string($optionId)) {
									//pass
								} elseif (is_array($optionId)) {
									$optionId = '';
								} else {
									$optionId = '';
								};
								if ($attribute->usesSource()) {
									$optionText = $attribute->getSource()->getOptionText($optionId);
								};
								if (strlen($optionText) > 1 ){
								} else {
									$optionText = 'N/A';
								};
							?>
							<span class="product-item-name"><?php echo $optionText; ?></span>
						</td>
						
						
						<td data-th="<?php echo $block->escapeHtml(__('Thickness')) ?>" class="col item" >
							<?php
								$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'thickness',$_item->getId());
								$optionId = $my_attr;
								$attribute = $_product->getResource()->getAttribute('thickness');
								if (is_string($optionId)) {
									//pass
								} elseif (is_array($optionId)) {
									$optionId = '';
								} else {
									$optionId = '';
								};
								if ($attribute->usesSource()) {
									$optionText = $attribute->getSource()->getOptionText($optionId);
								};
								if (strlen($optionText) > 1 ){
								} else {
									$optionText = 'N/A';
								};
							?>
							<span class="product-item-name"><?php echo $optionText; ?></span>
						</td>
						
						
						<td data-th="<?php echo $block->escapeHtml(__('Pitch')) ?>" class="col item" >
							<?php
								$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'pitch',$_item->getId());
								$optionId = $my_attr;
								$attribute = $_product->getResource()->getAttribute('pitch');
								if (is_string($optionId)) {
									//pass
								} elseif (is_array($optionId)) {
									$optionId = '';
								} else {
									$optionId = '';
								};
								if ($attribute->usesSource()) {
									$optionText = $attribute->getSource()->getOptionText($optionId);
								};
								if (strlen($optionText) > 1 ){
								} else {
									$optionText = 'N/A';
								};
							?>
							<span class="product-item-name"><?php echo $optionText; ?></span>
						</td>
						
						
						<td data-th="<?php echo $block->escapeHtml(__('Open Area')) ?>" class="col item" >
							<?php
								$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'open_area',$_item->getId());
								$optionId = $my_attr;
								$attribute = $_product->getResource()->getAttribute('open_area');
								if (is_string($optionId)) {
									//pass
								} elseif (is_array($optionId)) {
									$optionId = '';
								} else {
									$optionId = '';
								};
								if ($attribute->usesSource()) {
									$optionText = $attribute->getSource()->getOptionText($optionId);
								};
								if (strlen($optionText) > 1 ){
								} else {
									$optionText = 'N/A';
								};
							?>
							<span class="product-item-name"><?php echo $optionText; ?></span>
						</td>
						
						
						<td data-th="<?php echo $block->escapeHtml(__('AWG')) ?>" class="col item" >
							<?php
								$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'awg',$_item->getId());
								$optionId = $my_attr;
								$attribute = $_product->getResource()->getAttribute('awg');
								if (is_string($optionId)) {
									//pass
								} elseif (is_array($optionId)) {
									$optionId = '';
								} else {
									$optionId = '';
								};
								if ($attribute->usesSource()) {
									$optionText = $attribute->getSource()->getOptionText($optionId);
								};
								if (strlen($optionText) > 1 ){
								} else {
									$optionText = 'N/A';
								};
							?>
							<span class="product-item-name"><?php echo $optionText; ?></span>
						</td>
						
						
						<td data-th="<?php echo $block->escapeHtml(__('')) ?>" class="col item colhider" >
							<?php
								$addit = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'additinfo',$_item->getId());
							?>
							<span class="product-item-name"><?php echo $addit; ?></span>
							<?php $addit = ''; ?>
						</td>

					
						<td data-th="<?= $block->escapeHtml(__('Price')) ?>" class="col item">
						<?php if ($block->getCanShowProductPrice($_product)): ?>
							<?php if ($block->getCanShowProductPrice($_item)): ?>
								<?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
							<?php endif; ?>
						<?php endif; ?>
						</td>
					
					
						<td data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="col qty">
							<?php if ($_item->isSaleable()) : ?>
								<div class="control qty">
									<form data-role="tocart-form" action="<?php echo $this->getAddToCartUrl($_item); ?>" method="post">
										<input type="hidden" name="product" value="<?php echo $_item->getId(); ?>">
										<input type="hidden" name="related_product" id="related-products-field" value="">
										<div class="number-input">
											<a onclick="this.nextElementSibling.stepDown()" >&minus;</a>
												<input type="number" name="qty" min="1" value="<?= /* @escapeNotVerified */ $_item->getQty() * 1 ?>" title="<?= /* @escapeNotVerified */ __('Qty') ?>" class="input-text qty required" />
											<a onclick="this.previousElementSibling.stepUp()">+</a>
										</div>
										<?php echo $block->getBlockHtml('formkey')?>
										<button type="submit" title="Add to Cart" class="addtocart addbutt">Add <span class="fa fa-shopping-basket crat-icon"></span></button>
									</form>
								</div>

								<?php else: ?>
								<div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
								<span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
								</div>
							<?php endif; ?>
						</td>
						
						<td class="addtocart">
						</td>
					
					<?php endif; ?>
				</tr>
			
			
			<?php endif; ?>
				
				
				
			<?php if ($block->getCanShowProductPrice($_product) && $block->getCanShowProductPrice($_item) && trim($block->getProductPriceHtml( $_item, \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE	))): ?>
				<tr class="row-tier-price">
					<td colspan="2">
						<?= $block->getProductPriceHtml(
						$_item,
						\Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
						) ?>
					</td>
				</tr>
			<?php endif; ?>
		</tbody>
	<?php endforeach; ?>
<?php } else { ?>
	<tbody>
		<tr>
			<td class="unavailable"
				colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
				<?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
			</td>
		</tr>
	</tbody>
<?php }; ?>
</table>
</div>
<div id="validation-message-box"></div>

<form>
