<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<?php
if ($exist = ($block->getRecentlyViewedProducts() && $block->getRecentlyViewedProducts()->getSize())) {
    $type = 'widget-viewed';
    $mode = 'grid';

    $type = $type . '-' . $mode;

    $image = 'recently_viewed_products_grid_content_widget';
    $title = __('Recently Viewed');
    $items = $block->getRecentlyViewedProducts();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $rating = 'short';
    $description = ($mode == 'list') ? true : false;
}
?>
<?php if ($exist):?>
    <div class="block block-related widget block-viewed-products-<?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-title title block-title-tabs clearfix">
            <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <div class="block-content">
		    <div class="auto-height">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items products list items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info per-product">
						    <div class="images-container">
							    <div class="product-hover">
									<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
										<?php echo $block->getImage($_item, $image)->toHtml(); ?>
									</a>
									<?php if ($showWishlist || $showCompare || $showCart): ?>
										<div class="hover-box actions clearfix">
											<div class="product-item-inner show-box clearfix">
												<div class="product product-item-actions">
													<?php if ($showCart): ?>
														<div class="actions-primary actions-cart alotheme-tooltip">
															<?php if ($_item->isSaleable()): ?>
																<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																	<button class="action tocart primary button btn-cart"
																			data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																			type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																		<span class="tooltip"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																	</button>
																<?php else: ?>
																	<?php
																		$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																		$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																	?>
																	<button class="action tocart primary button btn-cart"
																			data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																			type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																		<span class="tooltip"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																	</button>
																<?php endif; ?>
															<?php else: ?>
																<?php if ($_item->getIsSalable()): ?>
																	<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
																<?php else: ?>
																	<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
																<?php endif; ?>
															<?php endif; ?>
														</div>
													<?php endif; ?>
													<?php if ($showWishlist || $showCompare): ?>
														<div class="secondary-addto-links add-to-links actions-secondary" data-role="add-to-links">
															<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
																<a href="#"
																   class="action towishlist alotheme-tooltip" data-action="add-to-wishlist"
																   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
																   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
																	<i class="fa fa-heart icon icons"></i>
																	<span class="tooltip"><?php /* @escapeNotVerified */ echo __('Wish List')?></span>
																</a>
															<?php endif; ?>
															<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
																<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
																<a href="#" class="action tocompare alotheme-tooltip"
																   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
																   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
																	<i class="fa fa-retweet icon icons"></i>
																	<span class="tooltip"><?php /* @escapeNotVerified */ echo __('Compare')?></span>
																</a>
															<?php endif; ?>
														</div>
													<?php endif; ?>
												</div>
											</div>
										</div>
									<?php endif; ?>
								</div>
								
								<div class="product details products-textlink product-item-details clearfix">
									<?php /* @escapeNotVerified */ echo $block->getProductPriceHtml(
										$_item,
										\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE,
										\Magento\Framework\Pricing\Render::ZONE_ITEM_LIST,
										[
											'price_id_suffix' => '-' . $type
										]
									) ?>
									<?php if ($rating): ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $rating) ?>
									<?php endif; ?>
									<p class="product-item-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</p>
								</div>
							</div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
			</div>
        </div>
    </div>
<?php endif;?>
