<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<style>
img:hover {
	opacity: 0.8;
	filter: alpha(opacity=80);
}
</style>
<?php 
$host =  "windows.ci3uj2kvqvcg.eu-west-2.rds.amazonaws.com" ;									// Host name or ip
$port = "3306";																					// Port number
$username = "readonly" ;																		// Connection username
$password = "OVlcP5xzcfy3OcuH" ;																// Connection password
$database = "just_stainless1";																	// Database name
$conn = new mysqli($host, $username, $password, $database);										// Create connection
if ($conn->connect_error) {die("Connection failed: " . $conn->connect_error);}					// Check connection, if broken then display the error
$sql = "SELECT * FROM img_gallery WHERE js_chairs = 1 ORDER BY img_gallery.`index` ASC;";		// select all from the table
$result = $conn->query($sql);																	// use $result as the variable for the connection and data select
if ($result->num_rows > 0) { 																	// check there is data in the table (Must be more than 1)
?>
<style>
.gallery_image {
	max-height: 300px;
	max-width: 300px;
}
</style>
<div class="container">
<div class="row">
	<div class="col cms-content"><h1>Chairs Gallery</h1></div>
</div>
<div class="row">

	<div align="left" class="col-md-6">
	We have chairs in varying materials and finishes:
	
	<div class="row">
		<div class="col-md-6">
			<ul>
				<li>Brass</li>
				<li>Copper</li>
				<li>Antique Copper</li>
			</ul>
		</div>
		<div class="col-md-6">
			<ul>
				<li>Antique Brass</li>
				<li>Patinated Copper</li>
				<li>Patinated Brass</li>
			</ul>
		</div>
	</div>
	Give us a call quoting the image number and we'll be happy to help.<br>
	</div>

	<div align="left" class="col-md-6">
		<a href="https://js-projects.s3.eu-west-2.amazonaws.com/juststainless_chairs.zip" target="_blank"><strong>Click Here to download all of the full resolution images</strong>&nbsp;&nbsp;(97mb)</a>
	</div>
	
</div>

<div align="center" class="row">
	<ul style="list-style:none;">
		<?php while($row = $result->fetch_assoc()) { ?>
			<li style="display: inline-block; padding: 15px;vertical-align: top;">
				<div>
					<?php $alttxt = "<br>" . $row["img_note"]; ?>
					<?php echo "<a data-fancybox=gallery href=https://js-projects.s3.eu-west-2.amazonaws.com/" . $row["lrg_img_name"] . ">" ?>
					<img class="gallery_image lazyload" loading="lazy" <?php echo "data-src=https://js-projects.s3.eu-west-2.amazonaws.com/" . $row["sml_img_name"] . "></a>" ?>
					<?php echo $alttxt ?>
				</div>
			</li>
		<?php } ?>
	</ul>
</div>
</div>
<?php
} else { echo "Something Seems to be Wrong. We're working on it!"; }				//if theres nothing in the table to be displyed do this
$conn->close(); 																	//close connection to improve server performance
?> 

<script>
  if ('loading' in HTMLImageElement.prototype) {
    const images = document.querySelectorAll('img[loading="lazy"]');
    images.forEach(img => {
      img.src = img.dataset.src;
    });
  } else {
    // Dynamically import the LazySizes library
	console.log('boo!')
    const script = document.createElement('script');
    script.src =
      'https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.8/lazysizes.min.js';
    document.body.appendChild(script);
  }
</script>
