<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Template for displaying grouped product price
 */
?>
<?php
$minProduct = $block->getSaleableItem()
    ->getPriceInfo()
    ->getPrice(\Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE)
    ->getMinProduct();

if ($minProduct) {
    $amountRender = $block->getRendererPool()
        ->createAmountRender(
            $minProduct->getPriceInfo()->getPrice('final_price')->getAmount(),
            $minProduct,
            $minProduct->getPriceInfo()->getPrice('final_price'),
            ['include_container' => true]
        );
}
?>
<div class="price-box">
    <p class="minimal-price">
	Click for price variations
    </p>
</div>
