<?php 
$host =  "magetno2.ci3uj2kvqvcg.eu-west-2.rds.amazonaws.com";											// Host name or ip
$port = "3306";																							// Port number
$username = "admin";																					// Connection username
$password = "%'m4rB1301'%";																				// Connection password
$database = "magento2_db";																				// Database name

// EXPORT FILE TO PYTHON DIRECTORY
// RUN PYTHON SCRIPT - MH Thumbnail Search Processor.py
// UPLOAD TABLE IN NAVICAT
?>

<?php

	if (isset($_GET['pageno'])) {
		$pageno = $_GET['pageno'];
	} else {
		$pageno = 1;
	}
	$no_of_records_per_page = 360;
	//$no_of_records_per_page = 48;
	$offset = ($pageno-1) * $no_of_records_per_page;

	$conn=mysqli_connect("magetno2.ci3uj2kvqvcg.eu-west-2.rds.amazonaws.com","admin","%'m4rB1301'%","magento2_db");
	// Check connection
	if (mysqli_connect_errno()){
		echo "Failed to connect to MySQL: " . mysqli_connect_error();
		die();
	}

	$total_pages_sql = "SELECT COUNT(*) FROM new_thumbnail_search";
	$result = mysqli_query($conn,$total_pages_sql);
	$total_rows = mysqli_fetch_array($result)[0];
	$total_pages = ceil($total_rows / $no_of_records_per_page);

	$sql = "SELECT * FROM new_thumbnail_search ORDER BY name DESC LIMIT $offset, $no_of_records_per_page";
	$res_data = mysqli_query($conn,$sql);
	?>
		
	<div class="row">
		<div class="col">
			<p>Use our Thumbnail Search to browse a small image of all of our products to find what you're looking for</p>
			<h5>Page <?php echo $pageno ?> of <?php echo $total_pages ?></h5>
		</div>
	</div>

	
	<div class="row">
		<?php
		while($row = mysqli_fetch_array($res_data)){
			?>
			<a href="<?php echo $row["url_key"] ?>">
				<div class="thumb">
					<img width="80" height="80" alt="<?php echo $row["name"] . ' - ' . $row["sku"]?>" class="img185 lazyload" loading="lazy" data-src="<?php echo $row["thumbnail_image"] ?>" >
				</div>
			</a>
		<?php
		}
		mysqli_close($conn);
		?>
	</div>
	
	<div class="row" align="center">
		<ul class="pagination">
			<li class="<?php if($pageno <= 1){ echo 'disabled'; } ?>">
				<a href="?pageno=1">
					First
				</a>
			</li>
			<li class="<?php if($pageno <= 1){ echo 'disabled'; } ?>">
				<a href="<?php if($pageno <= 1){ echo '#'; } else { echo "?pageno=".($pageno - 1); } ?>">
					Prev
				</a>
			</li>
			<li style="pointer-events:none;">
				<a style="background:#bebebe;">
					<?php echo "Page ".$pageno ?>
				</a>
			</li>
			<li class="<?php if($pageno >= $total_pages){ echo 'disabled'; } ?>">
				<a href="<?php if($pageno >= $total_pages){ echo '#'; } else { echo "?pageno=".($pageno + 1); } ?>">
					Next
				</a>
			</li>
			<li class="<?php if($pageno >= $total_pages){ echo 'disabled'; } ?>">
				<a href="?pageno=<?php echo $total_pages; ?>">
					<?php echo "Last" ?>
				</a>
			</li>
			
			
		</ul>
	</div>
	<div class="row" align="center">
		<h5>Page <?php echo $pageno ?> of <?php echo $total_pages ?></h5>
	</div>	

<script>
  if ('loading' in HTMLImageElement.prototype) {
    const images = document.querySelectorAll('img[loading="lazy"]');
    images.forEach(img => {
      img.src = img.dataset.src;
    });
  } else {
    // Dynamically import the LazySizes library
	console.log('boo!')
    const script = document.createElement('script');
    script.src =
      'https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.8/lazysizes.min.js';
    document.body.appendChild(script);
  }
</script>
