<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<?php
$storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Store\Model\StoreManagerInterface');
$urlMedia = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<div class="block newsletter block-subscribe popup" style="display:none;">
	<div id="popup-newsletter">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-popup-validate-detail">
			<div class="block-content">
			    <div class="inner-content clearfix">
					<div class="block-title">
						<strong><span><?php echo __('Welcome to') ?></span></strong>
						<h2 class="big-size"><?php echo __('Expert') ?></h2>
					</div>
					<h2 class="promo-panel-text promo-text text-uppercase text-lage black"><?php echo __('Want to score') ?><span class="sale-off"><?php echo __('25% Off') ?></span><?php echo __('Your First Purchase') ?></h2>
					<h2 class="promo-panel-text promo-text text-lage-1 text-italic"><?php echo __('Simple Enter your Email below you’ll also be First to hear about Promotion Specials, And the Latset new Arrivals') ?></h2>
					<div class="subcribe-box newsletter-new clearfix">
						<div class="field newsletter input-box">
							<div class="control">
								<input name="email" type="email" id="newsletter-popup" class="input-text"
											placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
											data-validate="{required:true, 'validate-email':true}"/>
							</div>
						</div>
						<div class="actions">
							<button class="action subscribe button" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
								<span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
							</button>
						</div>
					</div>
					<h2 class="promo-panel-text promo-text text-lage-2 text-italic"><?php echo __('*Offer vaild for new email subscribes on fisrt purchase only. Code not vaild on personalized, sale, or promotional pieces') ?></h2>
					<div class="subscribe-bottom">
						<input type="checkbox" /><?php echo __('Don’t show this popup again'); ?>
					</div>
				</div>
			</div>
        </form>
    </div>
</div>
<script type="text/javascript">
	require(['jquery', 'jquery/jquery.cookie', 'Magento_Ui/js/modal/modal'], 
		function($, cookie, modal){
			if(!parseInt(Themecfg.newsletter.enabled)) return;
	        
	        (function(selector){
	            var popupCookie = $.cookie('popupNewsletterOff');
	            var overlay = Themecfg.newsletter.overlayColor;
	            if(!popupCookie || popupCookie == 'undefined'){
	                var $content = $(selector);
	                var color   = Themecfg.newsletter.background_color;
	                var timeDelay = parseInt(Themecfg.newsletter.timeDelay);
	                var autoClose = Themecfg.newsletter.autoClose;
	                var timeClose = timeDelay + parseInt(Themecfg.newsletter.timeClose);
	                var imageUrl = "<?php echo $urlMedia; ?>" + 'magiccart/newsletter/' + Themecfg.newsletter.background_image;
	                var popup   = $('#popup-newsletter', $content);
	                var pwidth  = Themecfg.newsletter.width;
	                var pheight = Themecfg.newsletter.height;
	                pwidth   = typeof pwidth  !== 'undefined' ? pwidth : 800;
	                pheight  = typeof pheight !== 'undefined' ? pheight : 400;
	                overlay  = typeof overlay !== 'undefined' ? overlay : '#363636';
	                if(Themecfg.newsletter.background_image) popup.css('background-image', 'url(' + imageUrl + ')');
	                else if(color) popup.css('background-color', color);
	                setTimeout( function() {
                        modal({
                            type: 'popup',
                            modalClass: 'popup-newsletter',
                            responsive: true, 
                            buttons: false                       	
                        }, popup);
	                    popup.modal('openModal');
	                    $(".modal-popup .modal-inner-wrap").css({ "width":pwidth, "height":pheight }); 
	                }, timeDelay);
	                if(Themecfg.newsletter.autoClose > 0) setTimeout(function(){$.fancybox.close()}, timeClose);
	                $('.subscribe-bottom input', popup).on('click', function(){
	                    if($(this).parent().find('input:checked').length){
	                        $.cookie('popupNewsletterOff', true);
	                    } else {
	                        $.cookie('popupNewsletterOff', undefined);
	                    }
	                });
	                if(Themecfg.newsletter.firstOnly > 0) $.cookie('popupNewsletterOff', true);
	                popup.find('.actions button').on('click', function(){
	                    $.cookie('popupNewsletterOff', true);
	                    $.cookie('popupNewsletterMessages', true, {domain: document.domain});
	                });
	            } else {
	                if($.cookie('popupNewsletterMessages')){
	                    var $messages = $('.messages').attr('id', 'popupNewsletterMessages').wrap( "<div></div>" );
                       	modal({
                            type: 'popup',
                            modalClass: 'popup-messages',
                            responsive: true, 
                            buttons: false                       	
                        }, $messages);
	                    $messages.modal('openModal');
	                    $.cookie('popupNewsletterMessages', '', {domain: document.domain});
	                }
	            }

	        })(".block-subscribe.popup");
	});
</script>
