<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/

// @codingStandardsIgnoreFile

/**
* Grouped product data template
*
* @var $block \Magento\Catalog\Block\Product\View\BaseImage
* @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
*/
?>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />

<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $grouped = $_product->load($_product->getId()); ?>
<?php $associatedProducts = $grouped->getTypeInstance()->getAssociatedProducts($grouped); ?>

<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$categories = $product->getCategoryIds(); /*will return category ids array*/
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    #echo $cat->getId();
	
	if ($cat->getId() == '27') { # DONE  ----------  CHANGE THIS WHEN I KNOW WHAT THE SHEET PRODUCT CATEGORY IS
	$tableNum = '1';
	} else {
	$tableNum = '0';
    };
};
?>

<?php $numRows = 0; # Set variable for adding header at certain points through table ?>

</form>

<section id="product__container" class="product__container">

<div class="mobile-info">
		<p><i>You may need to Scroll Left and Right for more product details</i></p>
</div>

<div class="productTable">

				<div class="productTable__search">
                    <label for="Search">Search for...</label>
					<div class="productTable__search-sku">
						<label for="SKU">SKU</label>
						<input id="skuInput" onkeyup="filterSku()" type="text" placeholder="SKUs...">
					</div>

					<div class="productTable__search-sku">
						<label for="Sizes">Sizes</label>
						<input id="sizeInput" onkeyup="filterSizes()" type="text" placeholder="Sizes...">
					</div>
				</div>

<?php if ($_hasAssociatedProducts){ ?>

<!-- table number is related to the type of product that will be shown. e.g. some products need diffrernt headeer fields like thickness, pitch etc. -->
		<?php if ($tableNum == '0'){ ?>

	<!-- 				CODE FOR THE NORMAL MENU  -->
					<div class="productTable__header ">
						<div class="productHead__1"><?= /* @escapeNotVerified */ __('Image') ?></div>
						<div class="productHead__2"><?= /* @escapeNotVerified */ __('Drawing') ?></div>
						<div class="productHead__3"><?= /* @escapeNotVerified */ __('SKU') ?></div>
						<div class="productHead__4"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
						<div class="productHead__5"><?= /* @escapeNotVerified */ __('Finish') ?></div>
						<div class="productHead__6"><?= /* @escapeNotVerified */ __('Grade') ?></div>
						<div class="productHead__7"><?= /* @escapeNotVerified */ __('Size') ?></div>
						<div class="productHead__8"><?= /* @escapeNotVerified */ __('Price') ?></div>

						<?php if ($_product->isSaleable()): ?>
							<div class="productHead__9"><?= /* @escapeNotVerified */ __('Qty') ?></div>
						<?php endif; ?>
					</div>


		<?php } else { ?>

		<!-- 				CODE FOR THE SHEET METAL MENU  -->
			<div class="productTable__header">
						<div class="productHead__sheet-1"><?= /* @escapeNotVerified */ __('Image') ?></div>
						<div class="productHead__sheet-2"><?= /* @escapeNotVerified */ __('Drawing') ?></div>
						<div class="productHead__sheet-3"><?= /* @escapeNotVerified */ __('SKU') ?></div>
						<div class="productHead__sheet-4"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
						<div class="productHead__sheet-5"><?= /* @escapeNotVerified */ __('Finish') ?></div>
						<div class="productHead__sheet-6"><?= /* @escapeNotVerified */ __('Grade') ?></div>
						<div class="productHead__sheet-7"><?= /* @escapeNotVerified */ __('Thickness') ?></div>
						<div class="productHead__sheet-8"><?= /* @escapeNotVerified */ __('Pitch') ?></div>
						<div class="productHead__sheet-9"><?= /* @escapeNotVerified */ __('Open Area') ?></div>
						<div class="productHead__sheet-10"><?= /* @escapeNotVerified */ __('AWG') ?></div>
                        <div class="productHead__sheet-11"><?= /* @escapeNotVerified */ __('') ?></div>
						<div class="productHead__sheet-12"><?= /* @escapeNotVerified */ __('Price') ?></div>

						<?php if ($_product->isSaleable()): ?>
							<div class="productHead__sheet-12"><?= /* @escapeNotVerified */ __('Qty') ?></div>
						<?php endif; ?>
					</div>
					
		<?php }; ?>
		

    <?php foreach ($associatedProducts as $_item): ?>
        
	<!-- 			SHOW ANOTHER HEADER EVERY 10 ROWS OF PRODUCTS -->

		<?php if ($numRows == 10 || $numRows == 20 ) {  ?>
			<div class="headGrouped">

				<?php if ($tableNum == '0'){ ?>

					<div class="productTable__header">
						<div class="productHead__1"><?= /* @escapeNotVerified */ __('Image') ?></div>
						<div class="productHead__2"><?= /* @escapeNotVerified */ __('Drawing') ?></div>
						<div class="productHead__3"><?= /* @escapeNotVerified */ __('SKU') ?></div>
						<div class="productHead__4"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
						<div class="productHead__5"><?= /* @escapeNotVerified */ __('Finish') ?></div>
						<div class="productHead__6"><?= /* @escapeNotVerified */ __('Grade') ?></div>
						<div class="productHead__7"><?= /* @escapeNotVerified */ __('Size') ?></div>
						<div class="productHead__8"><?= /* @escapeNotVerified */ __('Price') ?></div>

						<?php if ($_product->isSaleable()): ?>
							<div class="productHead__9"><?= /* @escapeNotVerified */ __('Qty') ?></div>
						<?php endif; ?>
					</div>
					
				<?php } else { ?>

					<div class="productTable__header">
						<div class="productHead__1"><?= /* @escapeNotVerified */ __('Image') ?></div>
						<div class="productHead__2"><?= /* @escapeNotVerified */ __('Drawing') ?></div>
						<div class="productHead__3"><?= /* @escapeNotVerified */ __('SKU') ?></div>
						<div class="productHead__4"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
						<div class="productHead__5"><?= /* @escapeNotVerified */ __('Finish') ?></div>
						<div class="productHead__6"><?= /* @escapeNotVerified */ __('Grade') ?></div>
						<div class="productHead__7"><?= /* @escapeNotVerified */ __('Thickness') ?></div>
						<div class="productHead__8"><?= /* @escapeNotVerified */ __('Pitch') ?></div>
						<div class="productHead__9"><?= /* @escapeNotVerified */ __('Open Area') ?></div>
						<div class="productHead__10"><?= /* @escapeNotVerified */ __('AWG') ?></div>
                        <div class="productHead__11"><?= /* @escapeNotVerified */ __('hello') ?></div>
						<div class="productHead__12"><?= /* @escapeNotVerified */ __('Price') ?></div>

						<?php if ($_product->isSaleable()): ?>
							<div><?= /* @escapeNotVerified */ __('Qty') ?></div>
						<?php endif; ?>
					</div>


				<?php }; ?>

		<!-- this div ends 'headGrouped' div --> </div>

        
		    <?php }  # End numRows if ?>


        <?php $numRows++; ?>
		
		
		
<!-- All product table - Not sheet products ------------------------------------------------------------------------------->
			<?php if ($tableNum == '0'): ?> 

				<div class="productTable__products <?= strtoupper($block->escapeHtml($_item->getSku())) ?> <?php 
					if (isset($_GET['q'])) { 
						if ( strtoupper($block->escapeHtml($_item->getSku())) == strtoupper($_GET['q']) ) { 

							echo 'bg-success'; 

						} else { 
							echo 'nope'; 
						};  
					} else { 
						echo 'Not searched'; 
					}; 
						?>">
					
 			<!--								 CODE TO GET THE IMAGE -->
			 <div class="productItem__1">
					<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsDesktop" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $image_url; ?>" />
						</a>
					</div>
			<!--								 CODE TO GET THE IMAGE OF DRAWING -->

					<div class="productItem__2">
					<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsDesktop" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $lrg_image_url; ?>" />
						</a>
					</div>

			<!--								 CODE TO GET THE SKU NUMBER -->
					<div class="productItem__3 sku__num">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getSku()) ?><a class="groupedAnchor" name="<?= $block->escapeHtml($_item->getSku()) ?>">&nbsp;</a></strong>
					</div>
			<!--								 CODE TO GET THE PRODUCT NAME -->
					<div class="productItem__4">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
					</div>
			<!--								 CODE TO GET THE FINISH -->
					<div class="productItem__5">
						<?php					
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'finish',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('finish');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>
						<span class="product-item-name "><?php echo $optionText; ?> </span>
					</div>

			<!--								 CODE TO GET THE GRADE -->
					<div class="productItem__6">
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'grade',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('grade');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>

						<span class="product-item-name"><?php echo $optionText; ?></span>

					</div>
			<!--								 CODE TO GET THE SIZE -->
					<div class="productItem__7 size_num">

						<?php
                            $my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'size',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('size');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
						</div>

						<!--								 CODE TO GET THE PRICE -->

					<div class="productItem__8">
						<?php if ($block->getCanShowProductPrice($_product)): ?>
							<?php if ($block->getCanShowProductPrice($_item)): ?>
								<?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
							<?php endif; ?>
						<?php endif; ?>
					</div>

					<?php if ($_item->isSaleable()) : ?>


					<div data-th="<?= $block->escapeHtml(__('Qty')) ?>" class="productItem__9">
							<?php if ($_item->isSaleable()) : ?>

								<span class="Control__qty">

									<form data-role="tocart-form" action="<?php echo $this->getAddToCartUrl($_item); ?>" method="post">
                                    <input type="hidden" name="product" value="25684">
                                    <input type="hidden" name="related_product" id="related-products-field <?php echo $numRows ?>" value="">
                                        <span class="number-input">
                                            <a onclick="this.nextElementSibling.stepDown()" >&minus;</a>
                                                <input type="number" name="qty" min="1" value="0" title="Qty" class="Quantity__value" />
                                            <a onclick="this.previousElementSibling.stepUp()">+</a>
                                        </span>
                                        <input name="form_key" type="hidden" value="Q2WGgHb4BFsDOFgd" />
                                        <button type="submit" title="Add to Cart" class="addtocart addbutt">Add <span class="fa fa-shopping-basket crat-icon"></span></button>		
									</form>
								</span>

                                

								<?php else: ?>
								<div class="stock unavailable productItem__9 " title="<?= /* @escapeNotVerified */ __('Availability') ?>">
									<span><?= /* @escapeNotVerified */ __('Out of stock') ?><	/span>
								</div>
							<?php endif; ?>
						</div>
						<?php else: ?>

						<div class="stock unavailable productItem__9" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
						    <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
						</div>

					<?php endif; ?>
					</td>
						<td class="addtocart">
					</td>


			<!-- end product table div -->
			
<!-- SHEET PRODUCT TABLE BELOW HERE ------------------------------------------------------------------------------------------------------------------------------------------------------------------->
			<?php else: # --------------------------------------------------------------------------------------------------------------------------- ?>

				<div class="productTable__products <?= strtoupper($block->escapeHtml($_item->getSku())) ?>">

				<!--								 CODE TO GET THE IMAGE -->
					<div class="productItem__sheet-1">
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_base_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsSheet" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $image_url; ?>" />
						</a>
					</div>
				
				<!--								 CODE TO GET THE IMAGE OF THE DRAWING -->
					<div class="productItem__sheet-2">
						<?php
						$imagewidth = 1000;
						$imageheight = 1000;
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$_productnew = $objectManager->get('Magento\Catalog\Model\Product')->load($_item->getId());
						$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
						$lrg_image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->resize($imagewidth, $imageheight)->keepTransparency(TRUE)->getUrl();
						$image_url = $imageHelper->init($_productnew, 'product_small_image')->setImageFile($_productnew->getFile())->getUrl();
						?>
						<a href="<?php echo $lrg_image_url; ?>" data-fancybox="groupedProductsSheet" data-caption="<?= $block->escapeHtml($_item->getSku()) ?>">
							<img class="child-image" style="width:70px;" src="<?php echo $lrg_image_url; ?>" />
						</a>
					</div>
					
				<!--								 CODE TO GET THE SKU NUMBER -->
					<div class="productItem__sheet-3 sku__num">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getSku()) ?><a class="groupedAnchor" name="<?= $block->escapeHtml($_item->getSku()) ?>">&nbsp;</a></strong>
					</div>
					
				<!--								 CODE TO GET THE product information  -->
					<div class="productItem__sheet-4">
						<strong class="product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
					</div>
					
					
				<!--								 CODE TO GET THE FINISH -->
					<div class="productItem__sheet-5">
						<?php					
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'finish',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('finish');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?> </span>
					</div>

				<!--								 CODE TO GET THE GRADE -->
					<div class="productItem__sheet-6">
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'grade',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('grade');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>

						<span class="product-item-name"><?php echo $optionText; ?></span>

					</div>
					
				<!--								 CODE TO GET THE SIZE -->
					<div class="productItem__sheet-7">

						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'size',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('size');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</div>

					
				<!--								 CODE TO GET THE PITCH -->
					<div class="productItem__sheet-8 size_num">
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'pitch',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('pitch');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<div class=groupedtablena>N/A</div>';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</div>
					
				<!--								 CODE TO GET THE OPEN AREA -->
					<div class="productItem__sheet-9" >

						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'open_area',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('open_area');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</div>
					
			<!--								 CODE TO GET THE AWG -->
					<div class="productItem__sheet-10" >
						<?php
							$my_attr = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'awg',$_item->getId());
							$optionId = $my_attr;
							$attribute = $_product->getResource()->getAttribute('awg');
							if (is_string($optionId)) {
								//pass
							} elseif (is_array($optionId)) {
								$optionId = '';
							} else {
								$optionId = '';
							};
							if ($attribute->usesSource()) {
								$optionText = $attribute->getSource()->getOptionText($optionId);
							};
							if (strlen($optionText) > 1 ){
							} else {
								$optionText = '<span class=groupedtablena>N/A</span>';
							};
						?>
						<span class="product-item-name"><?php echo $optionText; ?></span>
					</div>

					
			<!--				 CODE -->
					<div class="productItem__sheet-12" >
						<?php
							$addit = $this->getProduct()->getResource()->getAttributeRawValue($_item->getId(),'additinfo',$_item->getId());
						?>
						<span class="product-item-name"><?php echo $addit; ?></span>
						<?php $addit = ''; ?>


					</div>

			<!--				 CODE TO GET THE PRICE -->
					<div data-th="<?= $block->escapeHtml(__('Price')) ?>" class="productItem__sheet-12">
					<?php if ($block->getCanShowProductPrice($_product)): ?>
						<?php if ($block->getCanShowProductPrice($_item)): ?>
							<?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
						<?php endif; ?>
					<?php endif; ?>
					</div>
		
			
			
			<?php endif; ?>	
				
			<?php if ($block->getCanShowProductPrice($_product) && $block->getCanShowProductPrice($_item) && trim($block->getProductPriceHtml( $_item, \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE	))): ?>
				<div class="row-tier-price ">
					<td colspan="2">
						<?= $block->getProductPriceHtml(
						$_item,
						\Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
						) ?>
					</td>
				</div>


			<?php endif; ?>
                            
            </div>

	<?php endforeach; ?>

    <?php if ($tableNum == '0'){ ?>

<!-- 				CODE FOR THE NORMAL MENU  -->
                <div class="productTable__header ">
                    <div class="productHead__1"><?= /* @escapeNotVerified */ __('Image') ?></div>
                    <div class="productHead__2"><?= /* @escapeNotVerified */ __('Drawing') ?></div>
                    <div class="productHead__3"><?= /* @escapeNotVerified */ __('SKU') ?></div>
                    <div class="productHead__4"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
                    <div class="productHead__5"><?= /* @escapeNotVerified */ __('Finish') ?></div>
                    <div class="productHead__6"><?= /* @escapeNotVerified */ __('Grade') ?></div>
                    <div class="productHead__7"><?= /* @escapeNotVerified */ __('Size') ?></div>
                    <div class="productHead__8"><?= /* @escapeNotVerified */ __('Price') ?></div>

                    <?php if ($_product->isSaleable()): ?>
                        <div class="productHead__9"><?= /* @escapeNotVerified */ __('Qty') ?></div>
                    <?php endif; ?>
                </div>


    <?php } else { ?>

    <!-- 				CODE FOR THE SHEET METAL MENU  -->
        <div class="productTable__header ">
                    <div class="productHead__sheet-1"><?= /* @escapeNotVerified */ __('Image') ?></div>
                    <div class="productHead__sheet-2"><?= /* @escapeNotVerified */ __('Drawing') ?></div>
                    <div class="productHead__sheet-3"><?= /* @escapeNotVerified */ __('SKU') ?></div>
                    <div class="productHead__sheet-4"><?= /* @escapeNotVerified */ __('Product Name') ?></div>
                    <div class="productHead__sheet-5"><?= /* @escapeNotVerified */ __('Finish') ?></div>
                    <div class="productHead__sheet-6"><?= /* @escapeNotVerified */ __('Grade') ?></div>
                    <div class="productHead__sheet-7"><?= /* @escapeNotVerified */ __('Thickness') ?></div>
                    <div class="productHead__sheet-8"><?= /* @escapeNotVerified */ __('Pitch') ?></div>
                    <div class="productHead__sheet-9"><?= /* @escapeNotVerified */ __('Open Area') ?></div>
                    <div class="productHead__sheet-10"><?= /* @escapeNotVerified */ __('AWG') ?></div>
                    <div class="productHead__sheet-11"><?= /* @escapeNotVerified */ __('') ?></div>
                    <div class="productHead__sheet-12"><?= /* @escapeNotVerified */ __('Price') ?></div>

                    <?php if ($_product->isSaleable()): ?>
                        <div class="productHead__sheet-12"><?= /* @escapeNotVerified */ __('Qty') ?></div>
                    <?php endif; ?>
                </div>
                
    <?php }; ?>

    </section>


			<?php } else { ?>
				<tbody>
					<div class="">
						<td class="unavailable"
							colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
							<?= /* @escapeNotVerified */ __('No options of this product are available.') ?>
						</td>
					</div class="">
				</tbody>

			<?php }; ?>






<!-- Desktop Search Functions -->
<script>


function filterSku(){

	let input, filter, containerDiv, skuSelector, singleProduct;

	// get the input 
	input = document.getElementById("skuInput");

	// get the value of the input and transform to upper case
	filter = input.value.toUpperCase();

	// get the table container that fits around all the content 
	containerDiv = document.querySelector("#product__container");

	skuSelector = containerDiv.getElementsByClassName("sku__num");

	singleProduct = document.getElementsByClassName("productTable__products");

	for(i = 0; i < skuSelector.length; i++){
		a = skuSelector[i].innerText;
		//txtValue = a.textContent || a.innerText;

		if(a.toUpperCase().indexOf(filter) > -1){
			singleProduct[i].style.display = "";
		} else {
			singleProduct[i].style.display = "none";
		}
	}

        input.oninput = function () {
            document.getElementById("sizeInput").disabled = this.value != "";
        };


    
}


function filterSizes() {

  // Declare variables
  let input, filter, containerDiv, sizeContainer, singleProduct,sizeSelector;

  // get the input 
  input = document.getElementById("sizeInput");
  // get the value of the input and trnasform to upper case
  filter = input.value.toUpperCase();

  // get the table container that fits around all the content 
  containerDiv = document.querySelector("#product__container");

  // gets all of the table container child elements with the specified tag name  ------ tr = container for different menus
  sizeContainer =  containerDiv.getElementsByClassName("size_num");


  // gets the thead element with name thead grouped which is in the numrows 10 if statement
  singleProduct = document.getElementsByClassName("productTable__products");

  // Loop through all table rows, and hide those who don't match the search query
    for(i = 0; i < sizeContainer.length; i++){
            a = sizeContainer[i].innerText;
            //txtValue = a.textContent || a.innerText;

            if(a.toUpperCase().indexOf(filter) > -1){
                singleProduct[i].style.display = "";
            } else {
                singleProduct[i].style.display = "none";
            }
        }
        input.oninput = function () {
            document.getElementById("skuInput").disabled = this.value != "";
        };
  }

</script>

</div>
<div id="validation-message-box"></div>
<form>
