<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<style>
img:hover {
	opacity: 0.8;
	filter: alpha(opacity=80);
}
.gallery_image {
	max-height:200px;
}
</style>
<?php 
$host =  "windows.ci3uj2kvqvcg.eu-west-2.rds.amazonaws.com" ;									// Host name or ip
$port = "3306";																					// Port number
$username = "readonly" ;																		// Connection username
$password = "OVlcP5xzcfy3OcuH" ;																// Connection password
$database = "just_stainless1";																	// Database name
$conn = new mysqli($host, $username, $password, $database);										// Create connection
if ($conn->connect_error) {die("Connection failed: " . $conn->connect_error);}					// Check connection, if broken then display the error
$sql = "SELECT * FROM img_gallery WHERE js_bespoke = 1 ORDER BY img_gallery.`index` DESC;";		// select all from the table
$result = $conn->query($sql);																	// use $result as the variable for the connection and data select
if ($result->num_rows > 0) { 																	// check there is data in the table (Must be more than 1)
?>
<div class="row">
	<div class="col cms-content"><h1>Bespoke Parts Gallery</h1></div>
</div>
<div class="row">
	<div class="col">
		Just Stainless is a business run by <strong>Resurgem Engineering Co. Ltd.</strong> Resurgem are specialists in designing and manufacturing with a wide variety of materials including aluminium, stainless steel, mild steel, brass, copper, alloy, plastic etc. A family business established in 1970 with a long tradition for quality, our 25 staff in a workspace of 8500 sq ft are on hand for total customer satisfaction, and take great pride in their finished product.
	</div>
</div>
<br>
<div align="center" class="row">
		<?php while($row = $result->fetch_assoc()) { ?>
				<div class="col-lg-4 col-md-4 col-sm-6 col-xs-6" style="padding-bottom:15px; min-height:280px;">
					<?php //$alttxt = $row["img_note"]; ?>
					<?php $alttxt = mb_convert_encoding($row["img_note"], 'UTF-8', 'UTF-8'); // THIS STOPS UTF-8 ENCODING ERRORS ?>
					<?php echo "<a data-fancybox=gallery href=https://js-projects.s3.eu-west-2.amazonaws.com/" . $row["lrg_img_name"] . ">" ?>
					<img class="gallery_image lazyload" loading="lazy" <?php echo "data-src=https://js-projects.s3.eu-west-2.amazonaws.com/" . $row["sml_img_name"] . "></a>" ?>
					<?php echo "<br>" . $alttxt ?>
				</div>
		<?php } ?>
</div>
<?php
} else { echo "Something Seems to be Wrong. We're working on it!"; }				//if theres nothing in the table to be displyed do this
$conn->close(); 																	//close connection to improve server performance
?> 

<script>
  if ('loading' in HTMLImageElement.prototype) {
    const images = document.querySelectorAll('img[loading="lazy"]');
    images.forEach(img => {
      img.src = img.dataset.src;
    });
  } else {
    // Dynamically import the LazySizes library
	console.log('boo!')
    const script = document.createElement('script');
    script.src =
      'https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.8/lazysizes.min.js';
    document.body.appendChild(script);
  }
</script>
