<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
<style>
img:hover {
	opacity: 0.8;
	filter: alpha(opacity=80);
}
</style>
<?php 
$host =  "windows.ci3uj2kvqvcg.eu-west-2.rds.amazonaws.com" ;									// Host name or ip
$port = "3306";																					// Port number
$username = "readonly" ;																		// Connection username
$password = "OVlcP5xzcfy3OcuH" ;																// Connection password
$database = "just_stainless1";																	// Database name
$conn = new mysqli($host, $username, $password, $database);										// Create connection
if ($conn->connect_error) {die("Connection failed: " . $conn->connect_error);}					// Check connection, if broken then display the error
$sql = "SELECT * FROM img_gallery WHERE mach_gallery = 1 ORDER BY img_gallery.`index` DESC;";	// select all from the table
$result = $conn->query($sql);																	// use $result as the variable for the connection and data select
if ($result->num_rows > 0) { 																	// check there is data in the table (Must be more than 1)
?>
<style>
.gallery_image {
	max-height: 150px;
	max-width: 150px;
}
</style>
<div class="row">
	<div class="col cms-content"><h1>Machined Parts Gallery</h1></div>
</div>
<div class="row">
	<div class="col-md-12">
		All types of business sign etching and engraving, as well as metal labels, no smoking signs, company plaques and metal plates in brass, copper, bronze, and stainless steel.<br />We can produce work up to a maximum size of <strong>2000 x 1250mm</strong>, and reproduce any colour required.<br>Call us now on: <strong>0117 937 2846</strong> or email an enquiry to: <a href="mailto:sales@metalhardware.co.uk"><strong>sales@metalhardware.co.uk</strong></a></p>
	</div>	
</div>

<div class="row">
	<div class="col-md-12">
		<ul class="nav nav-pills">
			<li class="navButtons" role="presentation"><a href="/machined-parts">Click to go to the Machined Parts Category</a></li>
		</ul>
	</div>	
</div>

<div align="center" class="row">
	<ul style="list-style:none;">
		<?php while($row = $result->fetch_assoc()) { ?>
			<li style="display: inline-block; padding: 15px;vertical-align: middle;">
				<div>
					<?php $alttxt = $row["img_note"]; ?>
					<?php echo "<a data-fancybox=gallery href=https://js-projects.s3.eu-west-2.amazonaws.com/" . $row["lrg_img_name"] . ">" ?>
					<img class="gallery_image lazyload" loading="lazy" <?php echo "data-src=https://js-projects.s3.eu-west-2.amazonaws.com/" . $row["sml_img_name"] . "></a>" ?>
				</div>
			</li>
		<?php } ?>
	</ul>
</div>
<?php
} else { echo "Something Seems to be Wrong. We're working on it!"; }				//if theres nothing in the table to be displyed do this
$conn->close(); 																	//close connection to improve server performance
?> 

<script>
  if ('loading' in HTMLImageElement.prototype) {
    const images = document.querySelectorAll('img[loading="lazy"]');
    images.forEach(img => {
      img.src = img.dataset.src;
    });
  } else {
    // Dynamically import the LazySizes library
	console.log('boo!')
    const script = document.createElement('script');
    script.src =
      'https://cdnjs.cloudflare.com/ajax/libs/lazysizes/4.1.8/lazysizes.min.js';
    document.body.appendChild(script);
  }
</script>
